<a href="https://colab.research.google.com/github/Yumpop/ML_basic_Study/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B3%B5%EB%A3%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

소스코드 :  https://github.com/chulminkw/PerfectGuide

## 넘파이, 판다스

ndarray : N차원(Dimension)배열(array) 객체
np.array() - () 안에 리스트를 넣어야함

- ndarray 안의 데이터 값은 숫자, 문자열, 불 값등 모두 가능
    - ndarray내 데이터 타입은 특성상 같은 데이터 타입만 존재 가능
    - ex) int와 float형이 같이 존재할 수 없음
    - 만약 다른 데이터가 같이 존재할 경우 데이터가 큰 데이터로 바뀜
- 데이터 타입 확인 : ndarray.dtype()


1.   데이터 타입 변화
    - 대용량 데이터들을 다룰시 메모리 절약을 위해 형변환을 주로 함
    - astype()에 인자로 입력
    - ex) 0,1,2 와 같이 크지않는 범위의 숫자를 위해 64bit의 float형 보다는 8bit의 int형으로 변환

2. axis축 
    - axis 0 : 행방향
    - axis 1 : 열방향

In [17]:
import numpy as np 
array1= np.array([1,2,3])  # 1차원 - shape (3,)
array2 = np.array([[1,2,3],[2,3,4]]) # 2차원 - shape (2,3)

print(type(array1))
print(array1.shape)

print(type(array2)) 
print(array2.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)


In [24]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [26]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [33]:
array2 = np.array([[1,2,3],
                   [2,3,4]])
print(array2.sum())  # 전체 데이터를 각각 더함 : 15
print(array2.sum(axis=0)) # 행끼리 더함
print(array2.sum(axis=1)) # 열끼리 더함

15
[3 5 7]
[6 9]


1. ndarray 생성하기
    - np.arange(X) 
        - 0부터 X개의 숫자를 표현
    - np.zeros((X,Y)) - dtype의 default은 실수형
        - 0으로 X행 Y열의 배열을 만듬
    - np.ones((X,Y) - dtype의 default은 실수형
        - 1으로 X행 Y열의 배열을 만듬
2. reshape()
    - 차원을 변경
    - 인자에 -1을 부여하면 그 axis는 가변적으로 바뀜


In [40]:
se_array = np.arange(10)
print(se_array)
print(se_array.dtype, se_array.shape)

zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [50]:
array1 =  np.arange(10)
print(array1)
# shape 변환
array2 = array1.reshape(5,2)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [52]:
array1.reshape(4,5)
# 변환할 수 없는 형태가 주어지면 오류 발생

ValueError: ignored

In [57]:
array1 = np.arange(10)
array2 = array1.reshape(-1,5)
print(array2, '\n', array2.shape)

array3 = array1.reshape(5,-1)
print(array3, '\n', array3.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 
 (5, 2)


In [61]:
array1 = np.arange(5)

# 1차원을 2차원으로 변환
array2 = array1.reshape(-1,1)
print(array2, array2.shape)
print()

# 2차원을 1차원으로 변환
array3 = array2.reshape(-1,)
print(array3, array3.shape)

# reshape() 의 인자에 -1은 한 개만 사용 가능  

[[0]
 [1]
 [2]
 [3]
 [4]] (5, 1)

[0 1 2 3 4] (5,)


1. 인덱싱 방법
    - 특정 위치 단일값 추출
    - 슬라이싱
    - 팬시 인덱싱
        - 리스트로 인덱스집합을 지정하면 해당 인덱스의 값을 반환
    - 불린 인덱싱
        - 조건 필터링과 검색을 동시에 가능 

- 팬시 인덱싱

In [71]:
array1d = np.arange(start= 1, stop = 10)
array2d = array1d.reshape(-1,3)
print(array2d)
print()

array3 = array2d[[0,1],1]
print('array2d[[0,1],2] =>', array3.tolist()) # tolist는 리스트형태로 표현
print()

array4 = array2d[[0,2], 0:2]
print(array4.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[[0,1],2] => [2, 5]

[[1, 2], [7, 8]]


- 불린 인덱싱 
    - 메커니즘 
        1. 조건을 수행
        2. False값은 무시하고 True값에 해당하는 인덱스 값들만 저장
        3. 저장된 인덱스값으로 데이터값 조회

In [73]:
array1d = np.arange(start = 1, stop =10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [77]:
print(array1d>5) # 불린 데이터로 조건을 수행해서 ndarray 형태로 반환해줌
var1 = array1d
print(type(var1))

[False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [78]:
print(array1d)
array3 = array1d[array1d>5]         # 불린 인덱싱으로 값 찾기
print('array1d로 불린인덱싱을 한 결과값', array3)

[1 2 3 4 5 6 7 8 9]
array1d로 불린인덱싱을 한 결과값 [6 7 8 9]


1. 배열의 정렬
    - sort() : default은 오름차순, 내림차순은 [::-1]을 적용 
        - np.sort() : 원본 행렬은 유지한 채 원본행렬의 정렬된 행렬을 반환
        - ndarray.sort() : 원본 행렬 자체를 정렬한 상태로 반환
    - argsort()
        - 원본행렬을 정렬한 후 정렬하기 전 인덱스 반환

2. 2차원 배열에서 정렬
    - axis기반으로 정렬한다

3. 선형대수 연산
    - np.dot(A,B) - 행렬 내적
    - np.transpose(A) - 전치행렬

In [81]:
org_array = np.array([3,1,9,5])
print('원본행렬 : ', org_array)
print()

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 행렬', sort_array1)
print('np.sort()호출 후 원본 행렬', org_array)
print()

sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬', sort_array2)  # 반환된 행렬은 없고 원본이 바뀜
print('org_array.sort() 호출 후 원본 행렬', org_array)

원본행렬 :  [3 1 9 5]

np.sort() 호출 후 반환된 행렬 [1 3 5 9]
np.sort()호출 후 원본 행렬 [3 1 9 5]

org_array.sort() 호출 후 반환된 행렬 None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


In [82]:
sort_array1 = np.sort(org_array)[::-1]
print(sort_array1)

[9 5 3 1]


In [86]:
# argsort
org_array = np.array([3,1,9,5])
print(np.sort(org_array))

sort_indices = np.argsort(org_array)[::-1]
print('내림차순전 원본 행렬 인덱스', sort_indices)

[1 3 5 9]
내림차순전 원본 행렬 인덱스 [2 3 0 1]


In [88]:
# 각 사람의 인덱스와 동일한 사람이 점수를 가짐
# 점수를 정렬한후 사람들을 출력하기 원함
name_array = np.array(['jonhn', 'mike', 'sarch', 'kate', 'sam'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
print(sort_indices)

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

[0 2 4 1 3]
['jonhn' 'sarch' 'sam' 'mike' 'kate']
[78 84 88 95 98]
